### ISSUE TITLE
Why the boundings boxes ids are not used in the json files of the folder JSON?

### ISSUE THREAD

**Issue by piegu** [DS4SD/DocLayNet#15]
Hi,

the files `train.json`, `val.json`, `test.json` of the folder `COCO `(zip [DocLayNet core dataset](https://codait-cos-dax.s3.us.cloud-object-storage.appdomain.cloud/dax-doclaynet/1.0.0/DocLayNet_core.zip)) give the bouding boxes by image (through `image_id`), and each bounding box has an `id` and a category (through `category_id`).

To get the text of these bounding boxes, we need to open the corresponding json file in the folder JSON (zip [DocLayNet extra files](https://codait-cos-dax.s3.us.cloud-object-storage.appdomain.cloud/dax-doclaynet/1.0.0/DocLayNet_extra.zip)) but in the key `cells` of this json file, we do not find the bounding boxes ids: there are only the keys `bbox`, `text` and `font`.

It means that we need to compare the bouding boxes (compare lists of coordinates) in order to associate the texts to bounding boxes. :-(

Why the boundings boxes ids are not used in the json files of the folder JSON? Did I miss something? Thank you.

**Comment by cau-git** [comment]
Hi @piegu,
this is correct. These JSON files are parsed straight from the original PDFs. The text cells boxes are produced from the PDF code, and not created by annotation. As such, there is no explicit mapping from a given cell `bbox` to the object annotations in the COCO files, or vice versa. 

You can however produce this mapping with some simple intersection math. I.e. assigning all text cells to a coco object ID when a cell area is overlapping by more than 95% with an object would be a safe assumption. 

Sidenote: Some text cells in the JSON files may not overlap with any COCO annotation object, for example because they are present in the PDF code but actually invisible in the rendered page (outside of the page boundaries, white text on white background, empty strings, etc.)
